---
name: ardo-test
director_uuid: 8ff3f841-cf47-447c-9bf7-398bdd2c9cbe

update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time: 30000-600000
  max_in_flight: 3

compilation:
  cloud_properties:
    name: random
  network: cf3
  reuse_compilation_vms: true
  workers: 6

resource_pools:
- cloud_properties:
    name: random
  name: small_z1
  network: cf3
  size: 1
  stemcell:
    name: bosh-warden-boshlite-ubuntu-lucid-go_agent
    version: latest

releases:
- name: ardo-test 
  version: latest

networks:
- name: cf3
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.2.0/30
    reserved:
    - 10.244.2.1
    static:
    - 10.244.2.2
  - cloud_properties:
      name: random
    range: 10.244.2.4/30
    reserved:
    - 10.244.2.5
    static:
    - 10.244.2.6
  - cloud_properties:
      name: random
    range: 10.244.2.8/30
    reserved:
    - 10.244.2.9
    static: []

jobs:
- name: web_ui 
  templates:
  - name: web_ui
    release: ardo-test
  instances: 1
  resource_pool: small_z1
  networks:
  - name: cf3
    static_ips : 10.244.2.2
  properties:
    web_ui:
      port: 9000

