---
name: ardo

releases:
- name: bosh-vcloud-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-vcloud-cpi-release?v=20
  sha1: c5fd4982841fa7b51dc1a1cae711712f01dd5838
- name: ardo
  url: file://assets/ardo-0+dev.2.tgz

resource_pools:
- name: vms
  network: private
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-vcloud-esxi-ubuntu-trusty-go_agent?v=3169
    sha1: 85a46067588f825f18738667210eac34c0a4f3f1
  cloud_properties:
    cpu: 2
    ram: 4_096
    disk: 20_000
  env:
    bosh:
      # c1oudc0w is a default password for vcap user
      password: "$6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0"

disk_pools:
- name: disks
  disk_size: 20_000

networks:
- name: private
  type: manual
  subnets:
  - range: 192.168.100.0/24
    gateway: 192.168.100.1
    dns: [192.168.100.1]
    cloud_properties: {name: bosh-network} # <--- Replace with Network name

jobs:
- name: web_ui
  templates:
  - name: web_ui
    release: ardo
  instances: 1
  resource_pool: vms
  networks:
  - name: private
    static_ips: [192.168.100.4]
  properties:
    web_ui:
      port: 9000

cloud_provider:
  template: {name: vcloud_cpi, release: bosh-vcloud-cpi}

  mbus: "https://mbus:mbus-password@192.168.100.4:6868"

  properties:
    vcd:
      url: https://sandbox.pez.pivotal.io
      user: sding
      password: shaozhen
      entities:
        organization: sding-org
        virtual_datacenter: sding-ovdc
        vapp_catalog: pcf_catalog
        media_catalog: pcf_catalog
        media_storage_profile: vCD-vSAN-Capacity-01
        vm_metadata_key: cf-agent-env
      control: {wait_max: 900}
    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]  
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}


