---
name: ardo
director_uuid: cbd4b944-f941-46bb-80d1-51714f3c07fe

update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time: 30000-600000
  max_in_flight: 3

compilation:
  network: ardo
  reuse_compilation_vms: true
  workers: 4
  cloud_properties:
    ram: 2048
    disk: 8192
    cpu: 2

resource_pools:
- name: small_z1
  network: ardo
  size: 1
  stemcell:
    name: bosh-vcloud-esxi-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    ram: 1024
    disk: 10000
    cpu: 1

releases:
- name: ardo
  version: latest

networks:
  - name: ardo
    type: manual
    subnets:
      - range: 192.168.201.0/24
        gateway: 192.168.201.1
        dns: [192.168.201.1]
        reserved:
          - 192.168.201.60 - 192.168.201.254
        static:
          - 192.168.201.2 - 192.168.201.30
        cloud_properties: {name: ardo}

jobs:
- name: web_ui
  templates:
  - name: web_ui
    release: ardo
  instances: 1
  resource_pool: small_z1
  networks:
  - name: ardo
    static_ips : 192.168.201.2
  properties:
    web_ui:
      port: 9000
